changes to another template
IEEEComputerSocietyUNB/ieee-computer-society-unb pull request #29
Opened 2019-09-30 13:12 UTC by andersonvieiradonascimento

@alexandrebarbaruiva

2019-10-01 19:01 UTC, alexandrebarbaruiva requested changes

2019-10-01 19:01 UTC, alexandrebarbaruiva commented on config.py
> +SITENAME2 = 'IEEE CS UnB'
Informação redundante que não está sendo utilizada, caso não seja usada agora mesmo, remover

2019-10-01 20:01 UTC, andersonvieiradonascimento commented on config.py
> +SITENAME2 = 'IEEE CS UnB'
Beleza.

2019-10-01 20:13 UTC, andersonvieiradonascimento commented on config.py
> +SITENAME2 = 'IEEE CS UnB'
Variável inutilizada removida @alexandrebarbaruiva

2019-10-18 13:57 UTC, alexandrebarbaruiva commented
Template não condiz com o especificado em reunião. PR será fechada como acordado.

2019-10-18 13:57 UTC, closed without merging